### ISSUE TITLE
Who do we accept as instructors?

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/forum#13]
We have had someone apply to be an instructor, who is only in Portugal for a few months. This has lead to the question of what criteria is needed to teach. 

We currently have a [How to Recruit Instructors](https://github.com/LDSSA/wiki/wiki/Recruiting-and-Onboarding-New-Instructors) section, which assumed that every applicant already comes in with an instructors as a sponsor.

Beyond what is discussed in the wiki, I have a few questions: 

- How does someone who does not know us personally yet manage to become an instructor? (and do they at all)
- Can someone who is not in Portugal all the time become an instructor (not including past staff in this)
- Can someone "just teach", or are they expected to put work in at least one other AOR? (teaching being the "fun part")

**Comment by hershaw** [comment]
It wasn't clear from the article but the only way to come in is via a recommendation from an instructor. That means that if someone cold-calls us and asks to volunteer, an instructor must take the time to assess them and then feel comfortable with putting their name next to a sponsorship for them.

So I think that what needs to happen is that when someone new cold-calls us, there needs to be one extra step defined on the wiki which is "find a sponsor for that person" which translates to "find someone who is willing to take some time and do an initial assessment on them to the point that they feel comfortable providing a recommendation that they join the academy." Then we need to define exactly what that process would look like.

thoughts?

**Comment by dominguezmaria** [comment]
@hershaw, you're answering this question _"How does someone who does not know us personally yet manage to become an instructor? (and do they at all)"_, and I agree with you.
Makes sense that one of us takes the time to get to know the person better, eventually sponsor them, and this way we can onboard people who we don't already know.

Regarding the other two questions:
-  _"Can someone who is not in Portugal all the time become an instructor (not including past staff in this)"_
- _"Can someone "just teach", or are they expected to put work in at least one other AOR? (teaching being the "fun part")"_

I think these are trickier, because we need to define if we accept that a person can belong to the academy temporarily.
Ideally, we want that every person who participates in the academy, commits to it in a long-term way, so that they become part of the community that is being created.
Being in Portugal or not can be a proxy for the expected time that the person will actively participate in the community, but we already know that this is not always true: we both have people living abroad who belong to the community, and people who live in Portugal and have participated in past academy activities and are not so active in the community anymore.
So I think the fundamental question is if we accept people who just teach, don't participate in the academy in any other way (no work on other AORs) and then go.

My opinion on this is that, as long as we have a good amount of people who are long term committed to the community (which I believe we have atm), we can have some people who just teach and go. However, a person who is planning on joining the academy in a more permanent way and also wants to help with other responsibilities should aways be preferred to someone who just teaches and go.
My reasoning for this opinion is the following:
- Teaching is demanding enough, we don't need **every** instructor taking other responsibilities.
- Some instructors that participated in the Starters Academy since the beginning won't be participating this time, so I'm forecasting a very demanding recruitment work. This small flexibility might help a bit, and make the goal of recruiting everyone more feasible.
- In the specialisations, the responsibility of recruiting a team is on the spec. lead side, and it may be a bit too demanding for the spec. lead if we require them to bring in another 2 people who want to join the academy in the long term.

I'm also fine if we decide that everyone who teaches at the academy must express their wishes to belong to the community in the long term, but then, we should definitely update the [Recruiting and Onboarding New Instructors document](https://github.com/LDSSA/wiki/wiki/Recruiting-and-Onboarding-New-Instructors), and be much more explicit about the expectations that the Academy has for the instructors, other than teaching.

**Comment by PedroGFonseca** [comment]
Agreed with both on all points (that was easy).

**Comment by hershaw** [comment]
Going to reopen this until the appropriate documentation is updated in an attempt to make sure that the decisions make their way to some place useful 😄

**Comment by dominguezmaria** [comment]
Guys, so I suggest the process to recruit "unknown people" as volunteers to be the following.
If you're ok with this, I'll just copy and paste the paragraph below to the [Recruiting and Onboarding New Instructors](https://github.com/LDSSA/wiki/wiki/Recruiting-and-Onboarding-New-Instructors) document, after the "Quick chat with Sam and Ascensão", and close this issue.

**Someone approached us offering to help as a volunteer instructor**

In case no one in the organisation can vouch for the candidate, we need to get to know the candidate until someone is ready to be their sponsor.

For this, we'll need someone **who has already been an instructor in a previous edition of the Starters Academy**, to interview the candidate.
The interview should cover:
- Why do they want to help us?
- What kind of experience with data science do they have?
- Explain how the starters academy works: bootcamp (SLUs), specialisations (BLUs), hackathons.
- Explain the time commitment that being an instructor at the academy requires
- After explaining in a really detailed way what we're all about, ask about how do they want to participate in the starters academy and in our community: do they just want to teach a specific thing or are they available to help with other tasks? Do they want to belong to the community in the long-term or is this more a temporary thing?
- It is very important to communicate in this interview what is the nature of the volunteering work that we need at the academy: stick to what you've committed to!
We're going to trust in what the candidate tells us about the level of commitment that they want to have in the academy. The important part is that they understand that everything that one says they're doing and then end up not doing, is going to be done by another person in a tighter time frame. Thus, they should never be dishonest in the interviewing process because that will be bad for everybody.

This interview should not confirm if the candidate becomes an instructor or not. It should only be a test whether they show the knowledge to teach at the academy (in general) and is aligned with our values.
The two possible outcomes of this interview are:
- Positive: the interviewer thinks the candidate is a good fit for the academy; the interviewer becomes the candidate's sponsor; they can now be assigned to learning units in the next Starters Academy.
- Negative: the interviewer thinks the candidate is not a good fit, so we should communicate that the process is over.

Then, when we get to the phase of assigning instructors to learning units, we'll try to assign the candidate to whatever they've shown interest in.
In order to confirm the assignment, the candidate will have a final interview with 
a) another instructor, in case we're assigning this person to an SLU
b) the specialisation lead, in case they want to be assigned to a specialisation

The idea of this interview is to evaluate if the candidate really has the knowledge to teach this subject and to have a second and final opinion on the person.
The assignment only takes place if the second interviewer agrees with it.

Ideally, one of these two interviews happens in person.

Let me know what you think!

**Comment by PedroGFonseca** [comment]
One tricky thing is managing levels of commitment. How can we tell if they will be interested while things are fun and new, and then disappear at critical moments?

**Comment by dominguezmaria** [comment]
> One tricky thing is managing levels of commitment. How can we tell if they will be interested while things are fun and new, and then disappear at critical moments?

We don't have a way to tell that. But I guess that the problem also happens when someone already knows the candidate from before... It's a problem that exists for everybody who wants to join the academy.
So I'd say we need to trust them, and believe them if they say that they want to participate with a high level of commitment. The important part is that they understand that everything that one says they're doing and then end up not doing, is going to be done by another person in a tighter time frame. Thus, they should never be dishonest in the interviewing process because that will be bad for everybody.

**Comment by PedroGFonseca** [comment]
True. I think part of the interview should be to say exactly what you just said 😅

**Comment by dominguezmaria** [comment]
Nice, I've added those thoughts to the interview description!
Do you think it's good to go this way @PedroGFonseca ?

@hershaw , are you comfortable with me adding these guidelines to the recruitment doc and closing this issue?

💪

**Comment by hershaw** [comment]
All sounds good, we can definitely consider this one closed. However I'd like to raise a few things that we should keep an eye on:

1) If the sponsor of a new teacher is someone that has worked with them before, we should be more willing to give them more responsibility. For example, letting them lead on a specialization. 
2) If the sponsor has never worked with them before in a professional environment we should hedge our bets with the amount of work that we give them first.

What this would mean is that rather than give someone the lead position on a specialization the first time around we would assign them a single notebook in a BLU. That way if they flake out and disappear, we can recover from that.

Well done guys! Seems like the recruiting guidelines have been improved quite a bit! Thanks @PedroGFonseca  and @dominguezmaria for such a thoughtful discussion!

**Comment by dominguezmaria** [comment]
Agree with your comment @hershaw! Going to add that on the guide lines.
Yey, we're good to go!! 😄

**Comment by dominguezmaria** [comment]
The [Recruiting and Onboarding New Instructors](https://github.com/LDSSA/wiki/wiki/Recruiting-and-Onboarding-New-Instructors) document was updated, closing this issue!

Actually I can't! 😅 
@PedroGFonseca , may you do the honours, please?

**Comment by PedroGFonseca** [comment]
![](https://media.giphy.com/media/PcTzEWBzqiL5u/giphy.gif)
