### ISSUE TITLE
Should job posts be allowed by companies we do not know?

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/forum#14]
I was wondering about our [Guidelines for job posting](https://github.com/LDSSA/wiki/wiki/Job-Posting-Approval-%5BWIP%5D#ldsa-job-advertisement). 

Every once in a while a company will reach out with job opportunities. I can't vouch for the company, but would still be interested in listing it, without implicitly vouching for it. 

I would suggest (in addition to having the [questionnaire](https://github.com/LDSSA/forum/issues/11)) that we have a section in the job posting which is "instructors that vouch for this company". If there are any, so much the better. If there aren't, students must do extra diligence themselves, but it needn't be an automatic disqualifier.  

- Pros: more job opportunities 
- Cons: less curated job opportunities

**Comment by dominguezmaria** [comment]
Agreed, and the "Instructors that vouch for this company" section seems a good solution for this.

I like better, and think it's a more transparent way of doing things, if we communicate all the job postings that we receive to the community. Then, the extra layer of having instructors vouching for the opportunity, guarantees that we are doing what the community expects from us: sharing our thoughts about the role and the company.

We are liberal and paternalistic at the same time 😄

**Comment by hershaw** [comment]
Great! @PedroGFonseca and @dominguezmaria, what do you think of adding the following to the guidelines:

## Job Sponsorship Level

Jobs postings that would involve working directly with members of the LDSA community are always preferred because that would mean that we have someone that we know sponsoring the job. However, since jobs can exist outside of this small group that may be very good, we should still allow them to be posted.

So what we will do is define a Job Sponsorship Level that can be assigned to the job:

- Level 1: You would be working directly with or for the instructor making the Job Posting
- Level 2: The relationship of who you would be working for is a friend of a friend. For example, an instructor making the Job Posting has worked with the team lead at a previous job and can confirm that they have a high level of trust.
- Level 3: There is no direct professional relationship between the instructor making the Job Posting and any members of the team or company. You should have a very good reason for posting one of these that can make it through the approval process.

**Comment by PedroGFonseca** [comment]
All for it. Who is owning this?

**Comment by PedroGFonseca** [comment]
@hershaw I know you closed it, but I'm still curious as to my previous question😅
