### ISSUE TITLE
LDSSA Prep Course - Naming issue

### ISSUE THREAD

**Issue by minhhoang1023** [LDSSA/forum#16]
Hi everyone! We have a decision to make about the name of the course, because - in my opinion - it will influence the marketing and the position of the Academy regarding to it.

Here it goes:

Should we assume that it is (1) a Prep Course for the Academy (meaning that the niche will be targeting is more narrow and specific);

(2) approach it like an open-ended Python Course (although we are also teaching Git and Nimpy) and anyone could take it for free independently if they're applying to the Academy or not;

or

(3) use a term like LDSA Python Course, where we are assuming this is under the Academy, however we are open that anyone related to DS or not wants to take the course independently if they're applying  to the Academy or not.

Sorry if this seems like a "philosophical" question, but I think we should be aligned with the ultimate goal of the Academy. Meaning that each option will have a different approach and a different outcome (all in my perspective).

I would love to have your thoughts on this. However, we need to close this up until tomorrow so we (#marketing ) have time to work on this and come up with a plan and decide on which dates we are going to promote things (and have time - especially - to implement them).

We need to start promoting on Monday (or Tuesday) the most.

**Comment by dominguezmaria** [comment]
I feel that this should be:
* a preparation course for the Starters Academy
* where we will guide the participants through materials that will allow them to learn enough Python, Numpy, Linear Algebra and Git to be able to follow the Starters Academy
* ideally, the people participating in this course are doing so in order to prepare for the Starters Academy, but we should allow anyone to participate.

I think this because:
* If we were to build a course with the aim of teaching Python (or Linear Algebra, or Git), we would do it in a different format. In particular, it would probably be with the same configuration as the starters academy, where we build our own materials.
* We're interested in developing such a course in the future, we just didn't have enough time to prepare it before this Starters Academy and we thought it would be more valuable doing it this way than not doing it at all this time around. When we do prepare such course in the future, we should promote it in a different way :)
* If one is interested in learning Python (or Linear Algebra, or Git), for the sake of learning it and not to prepare for the Starters Academy, there will probably be better ways to do it: at a calmer pace, maybe in person and not remotely, all in the same platform (because we might need to use resources from different platforms to explain different things)...

**Comment by minhhoang1023** [comment]
Thanks @chi for your thoughts! Taking into account your comments and Sam's, I would suggest the name: LDSSA Data science Prep Course. 

1. By **LDSSA Prep Course**, we are stating that this is a preparation course specifically for the Starter Academy, like what @chi has explained excellently

2. By the word **Data Science**, we are opening up to a wider range of audience who is not aware of the Starter Academy. One of the main marketing strategies is to create a Facebook event. This aims to appeal to people who are interested in a new career path, but do not know about the Academy and even do not know if Data Science is an option for them. As such, we should state explicitly that this course will prepare them with enough knowledge to start learning Data Science, and that anyone with no prior Programming knowledge and not coming from an Engineering background can still join. 

Of course there is always a risk that people taking the course but then not applying to the Academy. However, we should also think the other way around, that some people with no awareness about Data Science and the Academy, would end up applying. Also, I am confident that for anyone who has invested time and money to take part in an intensive Data Science prep course, he/she is very likely to apply for the Academy since we are offering excellent materials and coaching at a fraction of the price.

Let me know about your opinions!

**Comment by hershaw** [comment]
Just here to echo the arguments put forth already. I agree that the course should be positioned as something whose purpose is to provide a path to success in our Starters Academy. If there were two names to chose from:

1. LDSSA Data Science Prep Course
1. LDSSA Prep Course

I would choose the **second one** because the "LDSSA" acronym already has Data Science in the name and it makes it a bit shorter which makes things a bit easier for marketing as well as easier to say and write.

That is all! @minhhoang1023 we'll leave it up to you to pick one of the two names and we go from there. Either one you choose, the important parts are being communicated.
