### ISSUE TITLE
LDSSA Prep Course - Financial help for students

### ISSUE THREAD

**Issue by minhhoang1023** [LDSSA/forum#17]
We need to decide to what extent we can offer help in terms of finance? There are several options as follows - feel free to suggest more:

1. Offer Dataquest promo code (we still need to wrap this up with Dataquest)
2. Subscribe to the team solutions ($25/month per user for Basic plan and $40 for premium plan)
3. Buy a few account and ask people to rotate between themselves (There are several drawbacks to this in terms of sharing & progress tracking so I don't think this is very ideal)

**Comment by hershaw** [comment]
Would be very interested to hear what people have to say about this but I think that the students should have a bit of skin in the game as well as their own dataquest accounts.

My favorite option would be to give them a promo code that would allow for a discount. That way we can provide them with a bit of help / incentives to sign up while at the same time ensuring that they have made a small investment that would hopefully increase the motivation to finish.

**Comment by minhhoang1023** [comment]
I agree with Sam on this. In this case we won't be restricted by the number of students we can accept.

**Comment by dominguezmaria** [comment]
**Option 1**
How much discount does the promocode give? How much do students end up paying with this option?
At a first glance this seems the best option.

**Option 2**
Who pays to whom with this option?
Do students need to pay us and then we pay Dataquest? If so, I don't like this option much, as it gives us extra work that we probably don't want at this point.

**Option 3**
Really don't like this one. First because it's not very honest, especially considering that Dataquest is giving us promocodes, in order for us to do it right :)
Then, because tracking progress is a great way to motivate the students in their learnings, so having to share accounts would be messy!

**Comment by hershaw** [comment]
We need to figure out the promo code thing! I'll open up a convo on slack about it since we have a few folks with contacts at data quest.

**Comment by PedroGFonseca** [comment]
We have a 50% off on DataQuest, is it viable/desirable to use Academy money to finance it further?

**Comment by hershaw** [comment]
Do we already have to discount code that we can distribute to the students?

As far as helping finance it, we've decided against it.

**Comment by PedroGFonseca** [comment]
This is the last we've heard from them, 12 days ago: 

```
Hi Pedro, sorry for my delay in follow-up. I have gotten approval to offer a special discount for your students!

We offer 1/2 price for their first 90 days of either the basic of the premium subscriptions. They simply need to write into hello@dataquest.io and request a coupon be added to their account.

I will draft a more official doc around this and share shortly!

Have a great week,
Celeste
```
