### ISSUE TITLE
LDSSA Prep Course - Support during the course

### ISSUE THREAD

**Issue by minhhoang1023** [LDSSA/forum#19]
On how the course should work, I believe that we should be offering the following two methods of support. They are crucial to the course success, while at the same time won't require much commitment from us. But still I'd want to confirm with you all if we have enough resources to do so.

**1. Slack Q&A**: We create a Slack channel to answer specific questions related to Dataquest's challenges via Slack, and also to encourage collaboration between students

**2. 1-hour live session per week**: We do a poll to see if there is enough people interested in attending. If so, we will hold a live session to answer more generic questions, e.g. When should we use classes, etc. From my learning experience, this is very useful and will help students integrate knowledge from different topics and develop a bigger picture apart from only knowing to solve coding challenges.

If you think there's any other thing we can offer that fits into our budget/availability, please feel free to suggest.

**Comment by hershaw** [comment]
I think that both of these are a great idea @minhhoang1023! 

I would suggest doing the following to close it up:

1. We let Carol know that we will provide these two methods of support so that she can use it in her marketing.
1. We create a spreadsheet that has slots for us to fill in for the duration of the course for the Q&A sessions as well as the live sessions. Then it is a matter of finding people to fill in the slots.

Once these things are done, go ahead and close up the issue! Nice work here!
