### ISSUE TITLE
Improving Student Success - Batch 2 Poll

### ISSUE THREAD

**Issue by KitCate** [LDSSA/forum#22]
Hi everyone!

There is a new wiki page with the results from a poll sent to the 20 students from batch 2 that didn't graduate asking about the obstacles these students struggled with during the academy. We received 9 answers that were summarised and used to suggest changes/actions for future editions that would help prevent student dropout/non graduation.

It would be great to have feedback from everyone, instructors and students, regarding these results and the suggestions for the future!

Here is the wiki page:
https://github.com/LDSSA/wiki/wiki/Poll-results-on-student-dropout-from-Batch-2

And here is the original poll:
https://forms.gle/TAiXBuRWsHeJ2oug7

**Comment by dominguezmaria** [comment]
Really good work on the poll, summarising the results and coming up with ideas! 👏 

Just a minor suggestion on the poll: the measure on how much of the academy did the students complete could be translated into activities, together with the percentages.
Example: `10% or less` = `completed half of the SLUs`
This is because when I read 10%, I don't really know how much of the academy that really is :)

Regarding the ideas on how to improve, let's schedule a meeting to define specific teaching actions that we can do this time around! 🤓

**Comment by KitCate** [comment]
Hi Chi! 
Thanks a lot for the feedback, you were right on your suggestion :) I added more details on how the percentages were calculated and some charts considering separately each activity. I hope the info is clearer now.
Scheduling a meeting sounds great, I'll talk to you!

**Comment by PedroGFonseca** [comment]
amazing work :)
