### ISSUE TITLE
Should we have separate brands for the LDSSA (Academy), and the LDSSA (Course)? 

### ISSUE THREAD

**Issue by PedroGFonseca** [LDSSA/forum#27]
We currently have two brands, LDSA, and LDSSA. 

However they are currently indistinguishable in the minds of students (and often our own). 

Should these brands be perhaps defined as something a bit more separate, for instance by re-branding one of them?

Also, should they have separate logos?

**Comment by thecarolmartins** [comment]
I believe it depends on the purpose we want for each. 

I would suggest rebranding the one we have - becoming the core one - with a slight adaptation for the LDSSA. It might be a change of color and adding the “Starters”. 

If we divide the logos and make them too different without creating a flow between them, it will confuse people because the real difference is “minimal” (the word Starters) and people might not understand why the two different logos. 

By maintaining flow, we will always be consistent even the viewer isn’t sure if it’s LDSA or LDSSA. this helps in creating a strong brand.

**Comment by hershaw** [comment]
it's true that most people use the brands interchangeably when talking about them. we should fix it and, as carol mentioned, what the nature of the connection between them should be. then we can have some guidelines on how similar to make the brand.

Is also dependent on wrapping up the vision part mentioned in #2 of which work is in progress.
