### ISSUE TITLE
Prep Course Retrospective

### ISSUE THREAD

**Issue by minhhoang1023** [LDSSA/forum#29]
As this is the first time we organized the Data Science Prep course, a retrospective would be very useful to know what went well and what could be better. Though there are a few lessons to learn from here and there, the course went pretty well and I am super happy that we have helped quite a few people to enter a whole new career path that they might have not been able to. So thank you everyone for your tremendous help and support (especially Chi and Pedro for the great idea)!

**Results**
We have 25 students who enrolled in the Prep Course ended up passing the exam. With this number alone, I think we really should continue with the course. Not only that the course would potentially feed 50% of qualified applicants to the Academy, it also opens the door for people from non-engineering background to start learning Data Science.

**What went well**
- **Marketing:** With only 2 weeks to promote the course, we managed to get 150+ people signed up thanks to the amazing work from the Marketing team!
- **Community:** I am very impressed with the level of engagement among the students. They read the wiki, followed the slack usage rules and proactively helped out fellow students without waiting for the instructors to come in
- **Organization:** The course started and ended as planned. 5 live sessions (4 weekly + 1 bonus to solve the first wave exams) also went smoothly

**What can be improved**
- **Curriculum**: After speaking with several students, I came to the conclusion that Dataquest's exercises are too basic and not enough to prepare them for the exam. We can still continue using Dataquest's learning materials, but definitely need to provide more advanced exercises that are on par with the exam
- **Expectation management**:
   - Time requirement: I've received complaints from students that they have spent much more than the 30 hours mentioned in the Prep Course wiki page, which were estimated as the amount of time required to go through the Dataquest mission only. So next time, preparation time for the entrance exam needs to be factored in as well
    - Difficulty level: Some students found the exam to be unexpectedly hard, even though I have warned them many times that it would be much difficult than Dataquest exercises. So more emphasis on this is definitely needed
- **Student participation:** Students are not asking enough questions! There was one week we received very few questions. Also, not many questions were raised in the live sessions. This might be due to the fact that Dataquest's exercises were so easy that students did not have the need to ask anything
- **Application process:** We had 150 students enrolled in the Slack workspace, yet quite a lot of them have dropped out at some point during the course. I think a big part of this is because we allowed basically everyone to enter in the beginning, without having to pay for Dataquest upfront. Next time we should be stricter in the application process, not to dilute the slack work space with inactive members and to be able to derive meaningful metrics (e.g. the percentage of students that pass the test)
- **Curriculum:** When selecting what would go into the Prep Course, I read through the exam but did not have the chance to actually do it - my bad on this one! So it is super important that the next person in charge of the Prep course to try out the exam in order to cover everything in the exam, and provide exercises that are equally hard.

If you have any comment, especially the instructors for Slack Q&A or live sessions, let me know :)

**Comment by hershaw** [comment]
Nice retrospective Minh! Thanks so much for putting it together! I've got a few comments:

- The course should be MUCH harder. I think that DataQuest will probably not be a good fit for us because their business model (monthly subscription) makes it difficult for them to make the courses as hard as they probably should be since the harder it is, the more people that drop dataquest, the less money they make.
- I think that we should make our own course next year. We can probably re-use the same portal and infrastructure that we're using this time around for the Academy to make our own python course exactly as difficult as it needs to be.

I've also had some conversations with other instructors who feel like the difficulty of the entrance exam was too easy partly because we needed to cater to the students of the python course. In order to get our first real answer on this one, we'll need to see how many of the 25 students that went through the prep course drop out on the bootcamp requirements which are VERY difficult.

All in all, excellent first try! Thanks so much to Minh for making all of this happen and for all of the instructors who contributed in the live sessions and otherwise!

**Comment by minhhoang1023** [comment]
Thanks for the comment, Sam! 

1. While Dataquest is a natural and good option to get started, it does not meet our requirements for the Academy, mostly because the exercises are too easy and come with step-by-step instructions. So I agree that we should create our own course next year, which should be very similar to the course you taught at Nova! This will give us the flexibility to adjust how hard we want it to be without depending on a third-party provider. 

2. I understand that some instructors would feel this way, as by making the exam harder, we would raise the bar and reduce the number of people dropping out due to their technical skills. At the same time, we also need to make sure that those who put in enough effort during the prep course can pass the exam. However, the first part, which is to ensure all successful applicants meet our standards and manage through the Academy, is much more important and should come first. 

As you said Sam, depending on the performance of those 25 prep course students as well as the ones that got into through second wave exam (since the first wave is closer what we are aiming for), we can see how hard the next exam should be. Then, the prep course should be designed accordingly (e.g. how much harder it should be, how long it should last, etc.) so that both goals are achieved.

**Comment by PedroGFonseca** [comment]
Outstanding retrospective indeed (and congratulations on the results)! 

I'm personally pro having our own set of content, especially as it would allow us to open source it and help anyone who wants to learn (DataQuest is not expensive, but the act of payment may still block some people). And indeed the level of difficulty of the materials needs to go up. 

I'd challenge the idea that the test was too easy though. When I first started in DS I would barely have passed this Python test. We will see how our 25 peeps and peepettes fare :)

**Comment by dominguezmaria** [comment]
@minhhoang1023 really nice retrospective :)

I think you guys have already mentioned the important points:
- Dataquest was waaay too easy
- Using custom content would be the ideal way to move forward
- Next time around we should have the exam ready before hand, so that the course can properly prepare the students for it
- It's important to understand how many of the prep course students are going to make it through the academy until the end, to see if the course was enough as preparation for the academy

Regarding the exam difficulty:
- the first one might have been a bit too hard, not because of the content but because of the way the questions were structured (there were many cases of _all or nothing_ in terms of points)
- the second wave might have been a bit too easy, given that: 1) it was heavily inspired on the first wave one, 2) we shared possible answers for the first wave exam, 3) the questions were better structured, i.e, it was possible to get partial points if the students didn't manage to solve a question as a whole

Just one thought about how do we evaluate the success of the prep course. Given the format we had this year, where there was too little time and too much to learn, I don't like to use the number of people who passed the academy's exam as a measure of success.
I'll even go a step further and say that having 25 people at the academy who learned Python through the prep course is much better than I was expecting...

We have many learnings to take from this prep course, and one of them is that we should definitely do it next year. And let's make sure that next year's one will be (even) better!

I think you did an amazing job with the prep course :)

**Comment by minhhoang1023** [comment]
@dominguezmaria Great comments! Yours pretty much summed up the main lessons for next year :)

I talked to some students and they also have the same view on the exam difficulty. The first one is hard, but not because of the question itself. If we can have the difficulty level of first wave with the structure of the second wave (e.g. partial credits, meaningful feedback), it would be just right.

**Comment by hershaw** [comment]
Well done with this retrospective everyone! This thread will be invaluable for next year so let's remember that it exists :)

**Comment by PedroGFonseca** [comment]
Getting some closure. 
@Juliana-R if there are things from this issue that should go into Batch 5 please add them as separate issues.
