### ISSUE TITLE
Podcast

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#30]
Here is a proposal for a podcast by Carol. From my end it looks good but I don't know anything about podcasts so some more feedback would be excellent!

https://docs.google.com/document/d/1Q3LLeMC57uvr7umbdCibxhhKlFOrUmcJ3Kt0lc5kq4E/edit?usp=sharing

**Comment by manuelfcreis** [comment]
Hey!

I think it's looking great. I have a couple of comments, by topic:

## Marketing:

- I feel like once a month could possibly be too little. Most podcasts/shows start-out with a fortnightly schedule. 
- How will the podcast be distributed? Should we account for promoted posts on social media for example? Will it be exclusively word of mouth? 


## Production

- Who will be the host?
- Who will be the editor?
- What kind of equipment will we be using?

I have done all of the above and have some equipment if anything is needed!

## Content

- I feel like hackathon highlights may be a bit lackluster for people not in the hackathon. Maybe something a bit more engaging would work, specially in generating community. Something like actually inviting listeners to do the hackathon and having a public place where they can share their approaches? This way, we could possibly share the hackathon highlights a couple of weeks later and it would be more engaging for listeners.
- What should actually be the approach for the topics? Just interviewing someone on a topic can be a bit dry. If the goal is to be information heavy I feel like it should be more led by the host and the interviewee(s) are more for coloring and additional information
- Another interesting type of content that could be done is actually interviewing professionals in the area. Asking them how they got where they are and getting deep into their area of expertise/day-to-day work.

**Comment by thecarolmartins** [comment]
Hi Manuel! 

Thanks for your feedback. It’s super useful to know that you have podcast knowledge :)

**Disclamer: I’m writing from my phone - sorry for typos and the crappy formatting**

Here are some answers:

*Feedback: I feel like once a month could possibly be too little.*
We know, but it’s not realistic for the team to assume a higher rate of episodes, unfortunately. Personally, I would love to have more episodes, but I can’t guarantee it. If you have any suggestions for that to happen, please let me know. :)

*How will the podcast be distributed?* 
I’m not 100% sure of what you mean, but it will be distributed in all major platforms. Jose is taking care of it, but your input would be super useful! We are newbies here! :)

*Should we account for promoted posts on social media for example? Will it be exclusively word of mouth?*
In terms of promotions we will be promoting via SM + email, eventually. I’m planning to use a free version of Wavve to create audio snippets. Of course, word of mouth is relevant, but we will use Social Media as our first choice.


*Who will be the host?*
I haven’t nailed all details, so this is TBD. What I was thinking was to have me and Jose as hosts to avoid overwhelming other team members, because we all have a lot in our plates. But I’m still thinking of this. Again, any suggestions are welcome! The recording sessions would be AT the Hackathon to make logistics easier.

*Who will be the editor?*
I’m still thinking abou this as well. Either me or Jose can do it on Audacity, but I’m not 100% sure (yet) that we can take that on us. Eventually, I was thinking about talking to El Presidente and Finances to ask if we could have some budget to outsource editing in Upwork, or even find someone to do an internship with us (restart or etic student? Or even Antonio Arroio ou EPCI?) ;)

*What kind of equipment will we be using?*
Once again, I’m still not there at this exact moment. I don’t have equipment at all, except for my iPhone and a Lavalier microphone. Eventually, I’ll get a Yeti Blue Nano, but I don’t know when. But, YES, we need your equipment :P


*I feel like hackathon highlights may be a bit lackluster for people not in the hackathon. Maybe something a bit more engaging would work, specially in generating community. Something like actually inviting listeners to do the hackathon and having a public place where they can share their approaches? This way, we could possibly share the hackathon highlights a couple of weeks later and it would be more engaging for listeners.*
I like the idea, but I feel that having outside people attending an hackathon is also not  fair for those who got in. And, to be honest, a hackathon is fun to those who are doing it - not those watching. There’s not much going on. I understand your point of view, and that’s why we’ve added that part towards the end. If our goal is to (1) establish LDSA as a Portuguese authority figure and (2) make the LDSSA desirable for cloning, we need to show what we do inside hackathons for both reasons. Whoever wants to replicate the LDSSA, I believe they have interest in knowing what happens inside. Does this make sense? But i agree that if we can get more creative it would work better. 

*What should actually be the approach for the topics? Just interviewing someone on a topic can be a bit dry. If the goal is to be information heavy I feel like it should be more led by the host and the interviewee(s) are more for coloring and additional information*
It’s a casual approach. That’s the main idea - kind of a conversation around the topic and the expertise of the instructor. It’s not a tutorial or something super heavy. It’s more a conversation rather than an interview. It’s about sharing experiences, hacks and tips that can help beginners, but in a casual way. I hope that I’m passing the main idea... 

*Another interesting type of content that could be done is actually interviewing professionals in the area. Asking them how they got where they are and getting deep into their area of expertise/day-to-day work.*
That was actually the initial plan, actually. But time passed and I believe we are short on time to make it happen in a way that is structured and coherent. However, considering the objectives we have, I don’t believe that is a big issue. If we focus on the “Starters” approach, this means that by releasing episodes that evolve around the exact topic we are teaching inside the Academy, we are providing a simultaneous contact with what is happening. Do you agree? However, if we can pull off having a bi-monthly podcast, it would make sense. But, honestly, I think it’s too much right now - from planning, to outreach, to logistics, to production, etc...

What I talked to Jose yesterday, because we had the same opinion/concern as you have was: that can be for season 2! :D We don’t know the goals for next batch. But what do we know are the objectives for this one - because of that we are making a (huge) effort to stay focused on it (the objective). If not, I would have all these different ideas lol

**Comment by ivopbernardo** [comment]
Awesome idea @thecarolmartins. I really feel that this is a spot yet to be filled in the portuguese DS landscape.

Regarding the podcast structure, having the main topic and the hackathon's highlights with the instructor might lead to the same "discussion". This is, the instructor may naturally talk about the hackathon during the topic discussion and the podcast may get convoluted. 

Is it feasible to invite the winning team from the hackathon to discuss their strategy? (I know that this might be a pain in terms of actually getting everyone together to do the podcast). My experience with podcasts (listener perspective!) is that podcasts with more than one guest are more engaging. 

If not, I think we should define more clearly what Hackathon's Highlights discussion will be. Some ideas to structure:
- Describing the dataset?
- Discuss data engineering strategies?
- Discuss models?
- Talk about the pitfalls in the data?

Nevertheless, awesome work :)

**Comment by ivopbernardo** [comment]
Also, maybe we can fit in there more special editions with partners 😁

**Comment by thecarolmartins** [comment]
Thanks @ivopbernardo! About the highlights, maybe I didn’t explain myself clearly - sometimes I forget that people can’t read my mind lol.

What I was thinking of doing is: talking and interviewing (briefly) students and instructors. It’s not about the learning part, but rather the experience, the challenges, the fun part, the winners, the tactics, the fun. What I would like to replicate in audio is the environment. Would that help in turning the podcast a good listening choice?

We could even interview the winners at the hackathon. I would like to concentrate all ops during the hackathon.

I hope this helps clarify :)

And keep commenting and adding feedback. it’s super useful!!

I’ll edit the document ASAP with those additional notes.

**Comment by thecarolmartins** [comment]
And oh, I forgot to mention - yes for the partners part. @hershaw what’s your input on this? Could we have a small break during the episode (maybe before the Hackathon Highlights), saying something like “This Hackathon was brought to you directly from XYZ. XYZ is a company that bla bla bla. Thank you for supporting our mission of <insert LDSA mission>.

This could be a good way to promote our mission and help establish us as an authority too. What do you think?

**Comment by manuelfcreis** [comment]
**Hackathon Highlights

So what I meant with the hackathon highlights was a couple of things, I’ll try make my reasoning a bit more clear:

- Listening to people talk about a hackathon may be a bit boring, specially if they’re discussing strategies of something you haven’t participated in
- Maybe a way of both **engaging** our audience and creating a community is to open up the hackathons. This would mean making them publicly available for anyone that wants to try them out by themselves after listening to the podcast. I personally don’t feel this would be unfair as the main benefit of the hackathon for academy members is the on-site interaction and feedback. I feel like it only furthers our brand as a community for data scientists
- This would also have the benefit of making hackathon highlights more interesting after participating. So my suggestion was two-fold:
	- First, make the regular episode hackathon section be an explanation of what the hackathon was and where the dataset is at
	- Make an *extra-episode* that would air two weeks after the original one, where the hackathon highlights would be shown, i.e. we could interview the winning team and review some strategies / pitfalls.


I feel all other questions were answered thoroughly, thanks! 😄
