### ISSUE TITLE
Onboarding wiki page

### ISSUE THREAD

**Issue by hershaw** [LDSSA/forum#31]
https://github.com/LDSSA/wiki/wiki/Batch3-Student-Onboarding

Here's the first draft. Anything that anyone wants to add?

**Comment by dominguezmaria** [comment]
We could add the following:
1. Catarina Freitas (@catarinacf), who is in charge of student success, is a very good point of contact too! Just to give an example, last time we talked, we thought about having study groups on the days before the hackathons, and since I won't be in person in all of them, she is a very good backup contact in that case.
2. Another important item in "Important stuff to do" is to join the students slack
3. If we have 2., where we mention the tech-setup, we could link the slack channel where they can ask for support. I know this will probably be in the student repo too, but it can still be useful!
